[package]
name = "shortest-path"
version = "0.1.0"
authors = ["Jarred Nicholls <jarred.nicholls@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2"
once_cell = "1"
snafu = "0.6"
